service: practice-crud-api
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}
custom:
  postsTableName: employee-table-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  getEmployee:
    handler: api.getEmployee
    name: get-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{empId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn
  createEmployee:
    handler: api.createEmployee
    name: create-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: post
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn
  updateEmployee:
    handler: api.updateEmployee
    name: update-emloyee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{empId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn
  deleteEmployee:
    handler: api.deleteEmployee
    name: delete-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{empId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt PostsTable.Arn
  getAllEmployee:
    handler: api.getAllEmployee
    name: get-all-employee
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: posts
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1